version: '3.8'
services:
  rabbitmq1:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672    #amqp
      - 15672:15672  #http
    network: 
      - drones-network
    volumes:
     - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
frontend:
  image: hmabdala/frontendvuejsdrones:lastest
  deploy: 
    replicas: 3
  ports:
    - 8080:8080
  network: 
    - drones-network
  environment:
    VUE_APP_API_URL: 
backend:
  image: hmabdala/frontendvuejsdrones:lastest
  deploy: 
    replicas: 3
  ports:
    - 8081:8081
  network: 
    - drones-network
  environment: 
    MAIL_HOST: smtp.gmail.com
    MAIL_SERVICE: smtp.gmail.com
    MAIL_PORT: 587
    MAIL_AUTH_LOGIN: fefohenriller@gmail.com
    MAIL_AUTH_PASSWORD: fiap2021
    API_PORT: 8081
    MAIL_CONSUMER: fernandodgatti@gmail.com
    AMQP_HOST: 
networks:
  drones-network:
    driver: overlay