version: "3"
services:
    frontend:
        image: hmabdala/frontendvuejsdrones:lastest
        deploy:
            replicas: 1
        ports:
           - 8080:80
        networks:
            - drones-network
        environment:
           - "VUE_APP_API_URL=frontend"
        depends_on:
         - backend
    backend:
        image: hmabdala/backendnodejsdrones:lastest
        deploy:
            replicas: 1
        ports:
           - 3000:3000
        networks:
            - drones-network
        environment:
            - MAIL_HOST=smtp.gmail.com
            - MAIL_SERVICE=smtp.gmail.com
            - MAIL_PORT=587
            - MAIL_AUTH_LOGIN=fefohenriller@gmail.com
            - MAIL_AUTH_PASSWORD=fiap2021
            - API_PORT=3000
            - MAIL_CONSUMER=fernandodgatti@gmail.com
            - AMQP_HOST=rabbitmq1:5672
        depends_on:
         - rabbitmq1
networks:
    drones-network:
        driver: overlay