version: '3.8'
services:
  rabbitmq1:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq1
    ports:
      - "8080:15672"
    network: 
      - drones-network
    volumes:
     - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
frontend:
  image: hmabdala/frontendvuejsdrones:lastest
  deploy: 
    replicas: 3
  ports:
    - 8080:8080
  network: 
    - drones-network
  environment:
    VUE_APP_API_URL: 
backend:
  image: hmabdala/frontendvuejsdrones:lastest
  deploy: 
    replicas: 3
  ports:
    - 8081:8081
  network: 
    - drones-network
  environment:
    MAIL_HOST:
    MAIL_SERVICE:
    MAIL_PORT: 
    MAIL_AUTH_LOGIN:
    MAIL_AUTH_PASSWORD:
    API_PORT:
    MAIL_CONSUMER:
    AMQP_HOST: 
networks:
  drones-network:
    driver: overlay